#
# Makefile for the Epson s1d13xxx framebuffer device drivers
#

O_TARGET := epsonfb.o

export-objs := s1d13xxxfb.o

obj-m  := $(O_TARGET)
obj-y  := s1d13xxxfb.o

include $(TOPDIR)/Rules.make

