//----------------------------------------------------------------------------
//
//  File generated by S1D13505CFG.EXE
//
//  Copyright (c) 2000,2001 Epson Research and Development, Inc.
//  All rights reserved.
//
//----------------------------------------------------------------------------

// Panel:  640x480 77Hz STN Single 8-bit (PCLK=25.175 MHz) 
// Memory:  DRAM (MCLK=25.175 MHz)


#define S1D_DISPLAY_WIDTH           640
#define S1D_DISPLAY_HEIGHT          480
#define S1D_DISPLAY_BPP             8
#define S1D_DISPLAY_SCANLINE_BYTES  640
#define S1D_PHYSICAL_VMEM_ADDR      0x00c00000L
#define S1D_PHYSICAL_VMEM_SIZE      0x200000L
#define S1D_PHYSICAL_REG_ADDR       0x00e00000L
#define S1D_PHYSICAL_REG_SIZE       0x100
#define S1D_DISPLAY_PCLK            25175
#define S1D_PALETTE_SIZE            256
#define S1D_REGDELAYOFF             0xFFFE
#define S1D_REGDELAYON              0xFFFF

#define S1D_WRITE_PALETTE(p,i,r,g,b)  \
{  \
    ((volatile S1D_VALUE*)(p))[0x24/sizeof(S1D_VALUE)] = (S1D_VALUE)(i);  \
    ((volatile S1D_VALUE*)(p))[0x26/sizeof(S1D_VALUE)] = (S1D_VALUE)(r);  \
    ((volatile S1D_VALUE*)(p))[0x26/sizeof(S1D_VALUE)] = (S1D_VALUE)(g);  \
    ((volatile S1D_VALUE*)(p))[0x26/sizeof(S1D_VALUE)] = (S1D_VALUE)(b);  \
}

#define S1D_READ_PALETTE(p,i,r,g,b)  \
{  \
    ((volatile S1D_VALUE*)(p))[0x24/sizeof(S1D_VALUE)] = (S1D_VALUE)(i);  \
    r = ((volatile S1D_VALUE*)(p))[0x26/sizeof(S1D_VALUE)];  \
    g = ((volatile S1D_VALUE*)(p))[0x26/sizeof(S1D_VALUE)];  \
    b = ((volatile S1D_VALUE*)(p))[0x26/sizeof(S1D_VALUE)];  \
}

typedef unsigned short S1D_INDEX;
typedef unsigned char  S1D_VALUE;

typedef struct
{
    S1D_INDEX Index;
    S1D_VALUE Value;
} S1D_REGS;

static S1D_REGS aS1DRegs[] = 
{
    {0x0023,0x80},   // Performance Enhancement Register 1
    {0x0001,0x50},   // Memory Configuration Register
    {0x0022,0x58},   // Performance Enhancement Register 0
    {0x0002,0x14},   // Panel Type Register
    {0x0003,0x00},   // MOD Rate Register
    {0x0004,0x4F},   // Horizontal Display Width Register
    {0x0005,0x03},   // Horizontal Non-Display Period Register
    {0x0006,0xFF},   // HRTC/FPLINE Start Position Register
    {0x0007,0x8F},   // HRTC/FPLINE Pulse Width Register
    {0x0008,0xDF},   // Vertical Display Height Register 0
    {0x0009,0x01},   // Vertical Display Height Register 1
    {0x000A,0x00},   // Vertical Non-Display Period Register
    {0x000B,0x00},   // VRTC/FPFRAME Start Position Register
    {0x000C,0x00},   // VRTC/FPFRAME Pulse Width Register
    {0x000E,0xFF},   // Screen 1 Line Compare Register 0
    {0x000F,0x03},   // Screen 1 Line Compare Register 1
    {0x0010,0x00},   // Screen 1 Display Start Address Register 0
    {0x0011,0x00},   // Screen 1 Display Start Address Register 1
    {0x0012,0x00},   // Screen 1 Display Start Address Register 2
    {0x0013,0x00},   // Screen 2 Display Start Address Register 0
    {0x0014,0x00},   // Screen 2 Display Start Address Register 1
    {0x0015,0x00},   // Screen 2 Display Start Address Register 2
    {0x0016,0x40},   // Memory Address Offset Register 0
    {0x0017,0x01},   // Memory Address Offset Register 1
    {0x0018,0x00},   // Pixel Panning Register
    {0x0019,0x00},   // Clock Configuration Register
    {0x001A,0x00},   // Power Save Configuration Register
    {0x001B,0x00},   // Miscellaneous Register
    {0x001C,0x00},   // MD Configuration Readback Register 0
    {0x001E,0x00},   // General IO Pins Configuration Register 0
    {0x001F,0x00},   // General IO Pins Configuration Register 1
    {0x0020,0x00},   // General IO Pins Control Register 0
    {0x0021,0x00},   // General IO Pins Control Register 1
    {0x0023,0x00},   // Performance Enhancement Register 1
    {0x000D,0x0D},   // Display Mode Register
};

