# Copyright (c) 2016, Sonos, Inc.
# SPDX-License-Identifier: GPL-2.0

UPTO_ROOT := ../..
include $(UPTO_ROOT)/mtools/master.mk

LIB_NAME          := libeventreporter
LIB_VER_MAJOR     := 1
LIB_VER_MINOR     := 0

LIB_CFILES += event_reporter.c

include $(LIB_MK)

include $(BOTTOM_MK)
