#
# Makefile for 1-wire bus master drivers.
#

obj-$(CONFIG_W1_MASTER_MATROX)		+= matrox_w1.o
obj-$(CONFIG_W1_MASTER_DS2490)		+= ds2490.o
obj-$(CONFIG_W1_MASTER_DS2482)		+= ds2482.o
obj-$(CONFIG_W1_MASTER_PXA3xx)		+= pxa3xx_w1.o
