O_TARGET	:= mesh.o
obj-y		:= iflist.o \
		   mainthread.o \
		   mc_cache.o \
		   mesh_neighbour.o \
		   message_queue.o \
		   messages.o \
		   module.o \
		   multicast_queue.o \
		   pkthandlers.o \
		   pktqueue.o \
		   prochandlers.o \
		   rrequest_cache.o \
		   rtable.o \
		   timers.o \
		   utils.o
obj-m		:= $(O_TARGET)

include $(TOPDIR)/Rules.make
